# 安全警告：这个文件包含敏感信息！
# 务必将它添加到 .gitignore 文件中，不要提交到版本控制！
[neo4j]
uri = "neo4j+s://1e53c988.databases.neo4j.io"
user = "neo4j"
password = "ZS-rBIrq-tN6CCQj6KpUksdPby16HFje9Fn_rvH_fLc"

[openai]
# qwen3-1.7b  免费
# api_key = "sk-0IjBfMN4z2p1uQh87303264a7fEd42E2A8Aa3e92330bA2Ff"
# api_base = "https://maas-api.cn-huabei-1.xf-yun.com/v1"
# model_id = "xop3qwen1b7"

# deepseek-v3.2  限时免费
api_key = "sk-SWIltByNYhFqYOup6f91Ce0e55Ec4f628f4940F4B4000b5a"
api_base = "https://maas-api.cn-huabei-1.xf-yun.com/v1"
model_id = "xopdeepseekv32"